apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-pod-sa
  namespace: twd-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: twd-apps
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: twd-apps
subjects:
- kind: ServiceAccount
  name: read-pod-sa
  namespace: twd-apps
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
