apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resource-hpa
  namespace: twd-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-demo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
